location = "bench-high-3"
server_id = 3
num_clients = 0
listen_address = "127.0.0.1"
listen_port = 8003
output_filepath = "./bench-logs/high/server-3.json"

[clock]
drift_rate_us_per_s = 5.0
uncertainty_us = 10
sync_interval_ms = 1
